#!/usr/bin/env python3
"""Auto-promote LOCAL-EDIT files from a project repo to claude-workflow master.

Reads drift check JSON output, identifies LOCAL-EDIT files with a master source,
and creates a PR on the claude-workflow repo with the project's improved versions.

Usage (CI):
    python3 tools/auto_promote.py \
        --drift-json "$DRIFT_OUTPUT" \
        --project-dir project \
        --project-repo Phygital-Tech-Stack/erp \
        --master-repo Phygital-Tech-Stack/claude-workflow

Usage (local dry-run):
    python3 tools/auto_promote.py \
        --drift-json "$(cat drift.json)" \
        --project-dir /path/to/erp \
        --project-repo Phygital-Tech-Stack/erp \
        --dry-run
"""
import argparse
import hashlib
import json
import os
import subprocess
import sys
from datetime import datetime, timezone


def find_promote_candidates(drift_data: dict) -> list[dict]:
    """Extract LOCAL-EDIT files that have a master_source (promotable)."""
    candidates = []
    for result in drift_data.get("results", []):
        if result.get("status") == "LOCAL-EDIT" and result.get("master_source"):
            candidates.append({
                "file": result["file"],
                "master_source": result["master_source"],
            })
    return candidates


def generate_branch_name(project_repo: str) -> str:
    """Generate a branch name like promote/erp/a1b2c3d4."""
    project_name = project_repo.split("/")[-1].lower()
    timestamp = datetime.now(timezone.utc).strftime("%Y%m%d%H%M%S")
    short_hash = hashlib.sha256(timestamp.encode()).hexdigest()[:8]
    return f"promote/{project_name}/{short_hash}"


def generate_pr_body(project_repo: str, candidates: list[dict]) -> str:
    """Generate the PR description with file table."""
    file_rows = "\n".join(
        f"| `{c['file']}` | `{c['master_source']}` |"
        for c in candidates
    )

    return f"""## Auto-Promote: LOCAL-EDIT changes from {project_repo}

**Source:** [{project_repo}](https://github.com/{project_repo})

The following managed files were modified in the project repo. These changes
may contain improvements worth adopting into the master workflow.

| Project File | Master Destination |
|---|---|
{file_rows}

### Review Checklist

- [ ] Check for project-specific references (hardcoded paths, domain terms)
- [ ] Verify changes are generic enough for all projects
- [ ] Run tests: `bash tests/test_diff.sh`
- [ ] Consider if placeholder resolution is needed

---
*Auto-generated by the drift check CI workflow.*
"""


def check_existing_pr(master_repo: str, project_repo: str) -> bool:
    """Check if an open promote PR already exists for this project."""
    project_name = project_repo.split("/")[-1]
    result = subprocess.run(
        [
            "gh", "pr", "list",
            "--repo", master_repo,
            "--state", "open",
            "--search", f"promote: LOCAL-EDIT changes from {project_name} in:title",
            "--json", "number",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        return False
    prs = json.loads(result.stdout) if result.stdout.strip() else []
    return len(prs) > 0


def create_promote_pr(
    candidates: list[dict],
    project_dir: str,
    project_repo: str,
    master_repo: str,
    dry_run: bool = False,
) -> str | None:
    """Create a PR on the master repo with promoted files.

    Returns the PR URL if created, None if skipped.
    """
    if not candidates:
        print("No promote candidates found.")
        return None

    if not dry_run and check_existing_pr(master_repo, project_repo):
        project_name = project_repo.split("/")[-1]
        print(f"Open promote PR already exists for {project_name}, skipping.")
        return None

    branch = generate_branch_name(project_repo)
    project_name = project_repo.split("/")[-1]
    title = f"promote: LOCAL-EDIT changes from {project_name}"
    body = generate_pr_body(project_repo, candidates)

    if dry_run:
        print(f"DRY RUN — would create PR:")
        print(f"  Branch: {branch}")
        print(f"  Title:  {title}")
        print(f"  Files:  {len(candidates)}")
        for c in candidates:
            print(f"    {c['file']} -> {c['master_source']}")
        return None

    # Configure git for CI environment
    subprocess.run(["git", "config", "user.name", "github-actions[bot]"], check=True, capture_output=True)
    subprocess.run(["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"], check=True, capture_output=True)

    # Create branch from main
    subprocess.run(["git", "checkout", "main"], check=True, capture_output=True)
    subprocess.run(["git", "pull", "origin", "main"], check=True, capture_output=True)
    subprocess.run(["git", "checkout", "-b", branch], check=True, capture_output=True)

    # Copy files from project to master locations
    for c in candidates:
        src = os.path.join(project_dir, ".claude", c["file"])
        dest = c["master_source"]  # Already relative to master root
        os.makedirs(os.path.dirname(dest), exist_ok=True)
        with open(src, "rb") as f_in:
            content = f_in.read()
        with open(dest, "wb") as f_out:
            f_out.write(content)
        subprocess.run(["git", "add", dest], check=True, capture_output=True)

    # Commit and push
    subprocess.run(
        ["git", "commit", "-m", f"promote: local edits from {project_name}"],
        check=True,
        capture_output=True,
    )
    subprocess.run(
        ["git", "push", "-u", "origin", branch],
        check=True,
        capture_output=True,
    )

    # Create PR
    result = subprocess.run(
        [
            "gh", "pr", "create",
            "--repo", master_repo,
            "--title", title,
            "--body", body,
            "--label", "promote-candidate",
            "--head", branch,
            "--base", "main",
        ],
        capture_output=True,
        text=True,
    )

    if result.returncode == 0:
        pr_url = result.stdout.strip()
        print(f"PR created: {pr_url}")
        return pr_url
    else:
        print(f"ERROR creating PR: {result.stderr}", file=sys.stderr)
        return None


def main():
    parser = argparse.ArgumentParser(description="Auto-promote LOCAL-EDIT files to master")
    parser.add_argument("--drift-json", required=True, help="Drift check JSON output (string)")
    parser.add_argument("--project-dir", required=True, help="Path to project checkout")
    parser.add_argument("--project-repo", required=True, help="GitHub repo (owner/name)")
    parser.add_argument("--master-repo", default="Phygital-Tech-Stack/claude-workflow")
    parser.add_argument("--dry-run", action="store_true", help="Print what would happen")
    args = parser.parse_args()

    drift_data = json.loads(args.drift_json)
    candidates = find_promote_candidates(drift_data)

    if not candidates:
        print("No LOCAL-EDIT files with master source found. Nothing to promote.")
        sys.exit(0)

    print(f"Found {len(candidates)} promote candidate(s):")
    for c in candidates:
        print(f"  {c['file']} -> {c['master_source']}")

    pr_url = create_promote_pr(
        candidates=candidates,
        project_dir=args.project_dir,
        project_repo=args.project_repo,
        master_repo=args.master_repo,
        dry_run=args.dry_run,
    )

    if pr_url:
        print(f"\nPromote PR: {pr_url}")


if __name__ == "__main__":
    main()
